python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Acropora_millepora/GCF_013753865.1_Amil_v2.1_genomic.fna -o PLE_identify/Acropora_millepora -p 32 >Acropora_millepora.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Ambystoma_mexicanum/GCA_002915635.3_AmbMex60DD_genomic.fna -o PLE_identify/Ambystoma_mexicanum -p 32 >Ambystoma_mexicanum.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Amphilophus_citrinellus/GCA_013435755.1_ASM1343575v1_genomic.fna -o PLE_identify/Amphilophus_citrinellus -p 32 >Amphilophus_citrinellus.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Anas_platyrhynchos/GCF_015476345.1_ZJU1.0_genomic.fna -o PLE_identify/Anas_platyrhynchos -p 32 >Anas_platyrhynchos.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Anolis_carolinensis/GCF_000090745.1_AnoCar2.0_genomic.fna -o PLE_identify/Anolis_carolinensis -p 32 >Anolis_carolinensis.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Aquila_chrysaetos_chrysaetos/GCF_900496995.4_bAquChr1.4_genomic.fna -o PLE_identify/Aquila_chrysaetos_chrysaetos -p 32 >Aquila_chrysaetos_chrysaetos.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Bufo_bufo/GCF_905171765.1.bufo.bufo.fna -o PLE_identify/Bufo_bufo -p 32 >Bufo_bufo.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Bungarus_multicinctus/GCA_023653725.1_ASM2365372v1_genomic.fna -o PLE_identify/Bungarus_multicinctus -p 32 >Bungarus_multicinctus.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Callorhinchus_milii/GCF_018977255.1_IMCB_Cmil_1.0_genomic.fna -o PLE_identify/Callorhinchus_milii -p 32 >Callorhinchus_milii.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Chionodraco_hamatus/GCA_009756495.1_Chamatus_v0.1_genomic.fna -o PLE_identify/Chionodraco_hamatus -p 32 >Chionodraco_hamatus.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Corvus_cornix_cornix/GCF_000738735.5_ASM73873v5_genomic.fna -o PLE_identify/Corvus_cornix_cornix -p 32 >Corvus_cornix_cornix.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Crocodylus_porosus/GCF_001723895.1_CroPor_comp1_genomic.fna -o PLE_identify/Crocodylus_porosus -p 32 >Crocodylus_porosus.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Cyprinus_carpio/GCF_018340385.1_ASM1834038v1_genomic.fna -o PLE_identify/Cyprinus_carpio -p 32 >Cyprinus_carpio.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Danio_rerio/GCF_000002035.6_GRCz11_genomic.fna -o PLE_identify/Danio_rerio -p 32 >Danio_rerio.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Drosophila_melanogaster/GCF_000001215.4_dorsophila_mello.fna -o PLE_identify/Drosophila_melanogaster -p 32 >Drosophila_melanogaster.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Equus_caballus/GCF_002863925.1_EquCab3.0_genomic.fna -o PLE_identify/Equus_caballus -p 32 >Equus_caballus.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Gadus_morhua/GCF_902167405.1_gadMor3.0_genomic.fna -o PLE_identify/Gadus_morhua -p 32 >Gadus_morhua.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Geotrypetes_seraphini/GCF_902459505.1_aGeoSer1.1_genomic.fna -o PLE_identify/Geotrypetes_seraphini -p 32 >Geotrypetes_seraphini.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Gopherus_evgoodei/GCF_007399415.2_rGopEvg1_v1.p_genomic.fna -o PLE_identify/Gopherus_evgoodei -p 32 >Gopherus_evgoodei.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Homo_sapiens/GCF_000001405.40_human.fna -o PLE_identify/Homo_sapiens -p 32 >Homo_sapiens.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Latimeria_chalumnae/GCF_000225785.1_LatCha1_genomic.fna -o PLE_identify/Latimeria_chalumnae -p 32 >Latimeria_chalumnae.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Monodelphis_domestica/GCF_000002295.2_MonDom5_genomic.fna -o PLE_identify/Monodelphis_domestica -p 32 >Monodelphis_domestica.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Myiopsitta_monachus/GCA_017639245.1_MMon_1.0_genomic.fna -o PLE_identify/Myiopsitta_monachus -p 32 >Myiopsitta_monachus.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Myotis_lucifugus/GCF_000147115.1_Myoluc2.0_genomic.fna -o PLE_identify/Myotis_lucifugus -p 32 >Myotis_lucifugus.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Neomonachus_schauinslandi/GCF_002201575.2_ASM220157v2_genomic.fna -o PLE_identify/Neomonachus_schauinslandi -p 32 >Neomonachus_schauinslandi.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Ophonus_ardosiacus/GCA_943142095.1_icOphArdo1.1_genomic.fna -o PLE_identify/Ophonus_ardosiacus -p 32 >Ophonus_ardosiacus.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Rana_temporaria/GCF_905171775.1_aRanTem1.1_genomic.fna -o PLE_identify/Rana_temporaria -p 32 >Rana_temporaria.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Salmo_salar/GCF_905237065.1_Ssal_v3.1_genomic.fna -o PLE_identify/Salmo_salar -p 32 >Salmo_salar.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Takifugu_rubripes/GCA_901000725.3_fTakRub1.3_genomic.fna -o PLE_identify/Takifugu_rubripes -p 32 >Takifugu_rubripes.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Tribolium_freemani/GCA_939628115.1_Tfree1.0_genomic.fna -o PLE_identify/Tribolium_freemani -p 32 >Tribolium_freemani.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Tursiops_truncatus/GCF_011762595.1_mTurTru1.mat.Y_genomic.fna -o PLE_identify/Tursiops_truncatus -p 32 >Tursiops_truncatus.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Xenopus_borealis/GCA_024363595.1_UCB_Xborealis_1_genomic.fna -o PLE_identify/Xenopus_borealis -p 32 >Xenopus_borealis.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Xenopus_laevis/GCF_017654675.1_Xenopus_laevis_v10.1_genomic.fna -o PLE_identify/Xenopus_laevis -p 32 >Xenopus_laevis.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Xenopus_tropicalis/GCF_000004195.4_UCB_Xtro_10.0_genomic.fna -o PLE_identify/Xenopus_tropicalis -p 32 >Xenopus_tropicalis.log 2>&1
python3 Portable_PLESearch.py -hmm ./PLE.hmm -g /home/li/genomedb/Zootoca_vivipara/GCF_011800845.1_UG_Zviv_1_genomic.fna -o PLE_identify/Zootoca_vivipara -p 32 >Zootoca_vivipara.log 2>&1
